name: Despliegue a GCP

on:
  push:
    branches:
      - develop  # Cambia esto si estás utilizando otra rama
env:
  # Variables de ambiente
  ENV_VAR_1: '{ "type": "service_account", "project_id": "bubbly-journey-394223", "private_key_id": "b2639740fa283bbbfce2c57b72bdec0d402b6902", "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDPvjTXoN1Pu3yF\nW+xf/5WA799oOGy9DLNgk22QF+DHQ5Sq4zi697CpiUl3NoM9z7nsFLliO45rQDZM\nyfXzl7nbxFE04SfLA6wYtQk44ssbfqpbItRqmIsuoYU4GhKl/YaBwIoB7KX9nJP1\n8abCPi6t4ADGGb5OdBmlE7NSeR3YgyB2u1zS+tcSMurAFtUkeYXZ3OlizdJH0+M6\nc2Mq/tlf6zBzdLWw+ULmhNiBFPbsgaSNKlfBq9Gx8b1vQNU6/zyCmheMZx85r+8O\nCSWUITOBVaIr3wDmBcKflIWOBdkKPkeRDhUqHD5yLaArsl5LozpAh0XU7JRsJicj\nZmFDUlPTAgMBAAECggEAWTTGICnVnt1VdTap4/cuTbWza19/YhbIGBp2m7+FKEve\n1RrJS4/87nAjeeuQo8RFhBjKGmKUn31tU8ANu1JV3wcID/r3SXgEOH/Uu/a3XNEh\neg0UxclHSvjU6ehYRar+TU1OddEW3jaUWrIv940YIlXkPyziyXGVaYtyH2Ie7M9r\no8I+WjqI1Y+ptNl4kA3m1KHYW2/NJJH+4sipeurlMxXK3uVgwsrox2YTcjTjusK5\nTEkyPwbLtyfSt3JWDFDesisMcrO/SLfnUYVnvltT50+stYMcvpQO80cz+2tWHDIG\n8JwlkNawSEv/e7xuUr3w7osDnIWjUJ4VpZaOs1opgQKBgQDx1HGR74GsFYP8JPLb\neo3CZskIdJCJH13+mnxMeLMk57mhfg5YV1yqXUy/tCpcwHWNDNBJWWwBtymkrAa6\nS+82dDZbgLauoFEKsgp971Qn6zuBybpxKpZLTEp0vsnxMUi3/DhSBVs19R8Hu4NV\n8apSjUh5mEzE03k+55no/ehtoQKBgQDb6nHMhYz4jc7U8tcmUJY/CGKXugp8AV7i\nIBHCAoHY++MN2gQ20JTnZty0GN76KfNrw6UUyoVSpTjXukjPY4KwEIVCbLs14nYN\nTMKfiBmjJm88OgvMPxNuBC7M5+kX5pERcL9dUvaMTyurq83vA/guKLPjsUBHUzyK\nwjXFVuPE8wKBgDLOqIG5qSvHZXBvLtrv16K1R51QKCG3Bl98g4rpfPHPAZAtVMQ4\nro5YhcxtBM1x3gChZY1TjT6bBdPEFLHFTF/LcLQuybLMmdo+Z7fntW2hnWH6SQKH\nqQXu5GG8x961tQp6ojaRS4V9l2RfgAtpd5haeJSba92adInDzPFHjzKhAoGBAM7g\nPgtKuvF63U4/35tgheZn6e+XiJNc6rhHuMzMdP/8/HwkUoCKOPlyLz6QgvnMivwe\nQOZNGZxEZzOxPxsxHlioQePZy0cGcU1Tn2ZZrtxmpI+Af2a1E38UGj6SDxl3wZIp\ngSu2hs45D/jflss47bfmfEs+jBxMthBGYDTy5zN3AoGATCGa6IT2YHEXzPTtTKrP\nE68xtGZp//SZ9RvVDtHePMJ+D4wfV78R9P7CE4aJvVVbnmo33QNle3IX5V42vdjA\nfUlCzFAHtKg/+MTDH4+Fsy+vCSOR5BDFsk4Z37lVeZXB32qxT1J0xtrySPbQbLat\necYyvevynIS347u16nD0wIw=\n-----END PRIVATE KEY-----\n", "client_email": "col-the-main-candy-store-dev@bubbly-journey-394223.iam.gserviceaccount.com", "client_id": "110569847468971785388", "auth_uri": "https://accounts.google.com/o/oauth2/auth", "token_uri": "https://oauth2.googleapis.com/token", "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs", "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/col-the-main-candy-store-dev%40bubbly-journey-394223.iam.gserviceaccount.com", "universe_domain": "googleapis.com"}'
#  ENV_VAR_2: ${{ secrets.GOOGLE_PROJECT_ID }}
#  ENV_VAR_3: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
  
jobs:
  deploy_on_googles_app_engine:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código fuente
        uses: actions/checkout@v2
#      - name: Dependencias
#        run: npx gae-ayaml-env
#      - name: Variables
#        run: npx gae-ayaml-env
      - name: Reemplazo
        uses: 73h/gae-app-yaml-replace-env-variables@v0.3
        env:
          SECRET_ONE: '{{ secrets.GCP_SEC }}'
          SECRET_TWO: ${{ secrets.GOOGLE_PROJECT_ID }}
        with:
          app_yaml_path: "app.template.yaml"
      - name: Variables
        run: npx gae-ayaml-env
      - name: test
        run: |
          echo "TEST TAMBIEN"
          echo $SECRET_ONE
          echo $ENV_VAR_1
          echo "TEST x2"

      - name: Autenticación con Google Cloud Platform
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: $GCP_SEC
          
#jobs:
#  deploy:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout del código fuente
#        uses: actions/checkout@v2
#
#      - name: Dependencias
#        run: npx gae-ayaml-env
#        
#      - name: Variables
#        run: npx gae-ayaml-env
#        
#      - name: Reemplazo
#        run: 73h/gae-app-yaml-replace-env-variables@v0.3
#
#      - name: Autenticación con Google Cloud Platform
#        uses: google-github-actions/setup-gcloud@v0.2.0
#        with:
#          project_id: ${{ env.ENV_VAR_3 }}
#
#      - name: Ejecutar despliegue
#        run: gcloud app deploy app.template.yaml --quiet  --project ${{ env.ENV_VAR_2 }} --version=develop
