name: Despliegue a GCP

on:
  push:
    branches:
      - develop  # Cambia esto si estás utilizando otra rama

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código fuente
        uses: actions/checkout@v2

      - name: Autenticación con Google Cloud Platform
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: tu-proyecto-gcp-id
        env:
          CLOUDSDK_AUTH_CREDENTIAL_FILE_CONTENT: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Mostrar variables de ambiente y secretos
        env:
          # Imprime las variables de ambiente
          ENV_VAR_1: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        run: |
          echo "Variables de ambiente:"
          env

      - name: Ejecutar despliegue
        run: gcloud --quiet config set project tu-proyecto-gcp-id && gcloud app deploy app.yaml --version=main
