name: Despliegue a GCP

on:
  push:
    branches:
      - develop  # Cambia esto si estás utilizando otra rama

env:
  # Variables de ambiente
  GCP: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
  GOOGLE_PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}
#  ENV_VAR_3: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
  
jobs:
  deploy_on_googles_app_engine:
    name: Deploy
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout del código fuente
        uses: actions/checkout@v2
#      - name: Dependencias
#        run: npx gae-ayaml-env
#      - name: Variables
#        run: npx gae-ayaml-env
      - name: Reemplazo
        uses: 73h/gae-app-yaml-replace-env-variables@v0.3
        env:
          SECRET_ONE: ${{ secrets.GCP_SEC }}
          SECRET_TWO: $GOOGLE_PROJECT_ID
        with:
          app_yaml_path: "app.template.yaml"
      - name: Variables
        run: npx gae-ayaml-env
      - name: test
        run: |
          echo "TEST TAMBIEN"
          echo $GOOGLE_PROJECT_ID
          echo $GCP
          echo "TEST x2"

      - name: Autenticación con Google Cloud Platform
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ env.GCP }}
      - name: Ejecutar despliegue
        run: |
            gcloud app create --region=us-central
            gcloud app deploy app.template.yaml --quiet  --project ${{ env.GOOGLE_PROJECT_ID }} --version=develop
          
#jobs:
#  deploy:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout del código fuente
#        uses: actions/checkout@v2
#
#      - name: Dependencias
#        run: npx gae-ayaml-env
#        
#      - name: Variables
#        run: npx gae-ayaml-env
#        
#      - name: Reemplazo
#        run: 73h/gae-app-yaml-replace-env-variables@v0.3
#
#      - name: Autenticación con Google Cloud Platform
#        uses: google-github-actions/setup-gcloud@v0.2.0
#        with:
#          project_id: ${{ env.ENV_VAR_3 }}
#
#      - name: Ejecutar despliegue
#        run: gcloud app deploy app.template.yaml --quiet  --project ${{ env.ENV_VAR_2 }} --version=develop
